// Master language list used by the auth-screen picker and the in-app
// settings dropdown. Order: English first (most common default), Dutch +
// Dutch (Flemish) next per the project's primary persona, then the rest
// alphabetically. Strings double as both the dropdown label and the
// value persisted in settings.language / localStorage.
export const LANGUAGES: string[] = [
  'English',
  'Babel',
  'Dutch',
  'Dutch (Flemish)',
  'Abkhaz',
  'Acehnese',
  'Acholi',
  'Afar',
  'Afrikaans',
  'Albanian',
  'Alur',
  'Amharic',
  'Arabic',
  'Armenian',
  'Assamese',
  'Avar',
  'Awadhi',
  'Aymara',
  'Azerbaijani',
  'Balinese',
  'Baluchi',
  'Bambara',
  'Baoulé',
  'Bashkir',
  'Basque',
  'Batak Karo',
  'Batak Simalungun',
  'Batak Toba',
  'Belarusian',
  'Bemba',
  'Bengali',
  'Betawi',
  'Bhojpuri',
  'Bikol',
  'Bosnian',
  'Breton',
  'Bulgarian',
  'Buryat',
  'Cantonese',
  'Catalan',
  'Cebuano',
  'Chamorro',
  'Chechen',
  'Chichewa',
  'Chinese (Simplified)',
  'Chinese (Traditional)',
  'Chuukese',
  'Chuvash',
  'Corsican',
  'Crimean Tatar (Cyrillic)',
  'Crimean Tatar (Latin)',
  'Croatian',
  'Czech',
  'Danish',
  'Dari',
  'Dhivehi',
  'Dinka',
  'Dogri',
  'Dombe',
  'Dyula',
  'Dzongkha',
  'Esperanto',
  'Estonian',
  'Ewe',
  'Faroese',
  'Fijian',
  'Filipino',
  'Finnish',
  'Fon',
  'French',
  'French (Canada)',
  'Frisian',
  'Friulian',
  'Fulani',
  'Ga',
  'Galician',
  'Georgian',
  'German',
  'Greek',
  'Guarani',
  'Gujarati',
  'Haitian Creole',
  'Hakha Chin',
  'Hausa',
  'Hawaiian',
  'Hebrew',
  'Hiligaynon',
  'Hindi',
  'Hmong',
  'Hungarian',
  'Hunsrik',
  'Iban',
  'Icelandic',
  'Igbo',
  'Ilocano',
  'Indonesian',
  'Inuktut (Latin)',
  'Inuktut (Syllabics)',
  'Irish',
  'Italian',
  'Jamaican Patois',
  'Japanese',
  'Javanese',
  'Jingpo',
  'Kalaallisut',
  'Kannada',
  'Kanuri',
  'Kapampangan',
  'Kazakh',
  'Khasi',
  'Khmer',
  'Kiga',
  'Kikongo',
  'Kinyarwanda',
  'Kituba',
  'Kokborok',
  'Komi',
  'Konkani',
  'Korean',
  'Krio',
  'Kurdish (Kurmanji)',
  'Kurdish (Sorani)',
  'Kyrgyz',
  'Lao',
  'Latgalian',
  'Latin',
  'Latvian',
  'Ligurian',
  'Limburgish',
  'Lingala',
  'Lithuanian',
  'Lombard',
  'Luganda',
  'Luo',
  'Luxembourgish',
  'Macedonian',
  'Madurese',
  'Maithili',
  'Makassar',
  'Malagasy',
  'Malay',
  'Malay (Jawi)',
  'Malayalam',
  'Maltese',
  'Mam',
  'Manx',
  'Maori',
  'Marathi',
  'Marshallese',
  'Marwadi',
  'Mauritian Creole',
  'Meadow Mari',
  'Meiteilon (Manipuri)',
  'Minang',
  'Mizo',
  'Mongolian',
  'Myanmar (Burmese)',
  'Nahuatl (Eastern Huasteca)',
  'Ndau',
  'Ndebele (South)',
  'Nepalbhasa (Newari)',
  'Nepali',
  'NKo',
  'Norwegian',
  'Nuer',
  'Occitan',
  'Odia (Oriya)',
  'Oromo',
  'Ossetian',
  'Pangasinan',
  'Papiamento',
  'Pashto',
  'Persian',
  'Polish',
  'Portuguese (Brazil)',
  'Portuguese (Portugal)',
  'Punjabi (Gurmukhi)',
  'Punjabi (Shahmukhi)',
  'Quechua',
  'Qʼeqchiʼ',
  'Romani',
  'Romanian',
  'Rundi',
  'Russian',
  'Sami (North)',
  'Samoan',
  'Sango',
  'Sanskrit',
  'Santali (Latin)',
  'Santali (Ol Chiki)',
  'Scots Gaelic',
  'Sepedi',
  'Serbian',
  'Sesotho',
  'Seychellois Creole',
  'Shan',
  'Shona',
  'Sicilian',
  'Silesian',
  'Sindhi',
  'Sinhala',
  'Slovak',
  'Slovenian',
  'Somali',
  'Spanish',
  'Sundanese',
  'Susu',
  'Swahili',
  'Swati',
  'Swedish',
  'Tahitian',
  'Tajik',
  'Tamazight',
  'Tamazight (Tifinagh)',
  'Tamil',
  'Tatar',
  'Telugu',
  'Tetum',
  'Thai',
  'Tibetan',
  'Tigrinya',
  'Tiv',
  'Tok Pisin',
  'Tongan',
  'Tshiluba',
  'Tsonga',
  'Tswana',
  'Tulu',
  'Tumbuka',
  'Turkish',
  'Turkmen',
  'Tuvan',
  'Twi',
  'Udmurt',
  'Ukrainian',
  'Urdu',
  'Uyghur',
  'Uzbek',
  'Venda',
  'Venetian',
  'Vietnamese',
  'Waray',
  'Welsh',
  'Wolof',
  'Xhosa',
  'Yakut',
  'Yiddish',
  'Yoruba',
  'Yucatec Maya',
  'Zapotec',
  'Zulu',
];

export const DEFAULT_LANGUAGE = 'English';
export const BABEL_LANGUAGE = 'Babel';
export const PREFERRED_LANGUAGE_KEY = 'preferredLanguage';

export const isBabelLanguage = (language?: string): boolean =>
  String(language || '').trim().toLowerCase() === BABEL_LANGUAGE.toLowerCase();

export const getAssistantLanguageInstruction = (language: string = DEFAULT_LANGUAGE): string => {
  const selectedLanguage = LANGUAGES.includes(language) ? language : DEFAULT_LANGUAGE;

  if (isBabelLanguage(selectedLanguage)) {
    return [
      '### LANGUAGE MODE: BABEL / MULTILINGUAL',
      '- Understand any language Boss uses, including mixed-language messages.',
      '- Respond in the same language Boss is currently using.',
      '- If Boss mixes languages, answer naturally in the same mix without forcing English.',
      '- If Boss asks for translation or multiple languages, provide the requested multilingual output.',
      '- Keep the office-persona tone intact in every language.',
    ].join('\n');
  }

  return [
    `### LANGUAGE MODE: NATIVE ${selectedLanguage.toUpperCase()}`,
    `- Respond natively in ${selectedLanguage} by default because this is Boss's selected language.`,
    '- Do not fall back to English unless Boss explicitly asks for English.',
    '- Still understand and process requests in any language Boss uses.',
    '- If Boss asks for translation or multilingual output, comply without changing the saved language.',
    '- Keep tool results factual and translate summaries/errors into the selected language.',
  ].join('\n');
};

export const getStoredLanguage = (): string => {
  try {
    if (typeof window === 'undefined') return DEFAULT_LANGUAGE;
    const v = window.localStorage.getItem(PREFERRED_LANGUAGE_KEY);
    return v && LANGUAGES.includes(v) ? v : DEFAULT_LANGUAGE;
  } catch {
    return DEFAULT_LANGUAGE;
  }
};

export const setStoredLanguage = (lang: string): void => {
  try {
    if (typeof window === 'undefined') return;
    if (LANGUAGES.includes(lang)) {
      window.localStorage.setItem(PREFERRED_LANGUAGE_KEY, lang);
    }
  } catch {}
};
